apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
        - name: sample-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {}